const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let currentToken='',currentOrder=null,walletController=null,walletLoading=false;
async function renderMercadoPagoWallet(){
 if(!currentToken||walletLoading)return;const container=$('#walletBrick_container'),notice=$('#paymentNotice');if(!container)return;walletLoading=true;container.innerHTML='<small>Preparando pagamento seguro...</small>';
 try{if(typeof MercadoPago==='undefined')throw Error('O SDK do Mercado Pago não carregou. Atualize a página.');const r=await fetch('backend/api/mercadopago_checkout.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_token:currentToken})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Não foi possível preparar o pagamento.');if(d.paid){location.reload();return;}if(!d.preference_id)throw Error('Preference ID não recebido.');if(!d.public_key)throw Error('Public Key do Mercado Pago não configurada.');container.innerHTML='';const mp=new MercadoPago(d.public_key,{locale:'pt-BR'});const bricksBuilder=mp.bricks();walletController=await bricksBuilder.create('wallet','walletBrick_container',{initialization:{preferenceId:d.preference_id}});if(notice){notice.textContent='Pagamento processado no ambiente seguro do Mercado Pago.';notice.className='form-message';}}
 catch(e){container.innerHTML='<button id="retryMp" class="primary mp-pay">TENTAR CARREGAR MERCADO PAGO NOVAMENTE</button>';const retry=$('#retryMp');if(retry)retry.onclick=()=>{walletLoading=false;renderMercadoPagoWallet();};if(notice){notice.textContent=e.message;notice.className='form-message error';}}
 finally{walletLoading=false;}
}
async function syncReturnedPayment(){const qs=new URLSearchParams(location.search),paymentId=qs.get('payment_id')||qs.get('collection_id')||'';if(!paymentId||!currentToken)return;try{const r=await fetch('backend/api/mercadopago_sync.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_token:currentToken,payment_id:paymentId})}),d=await r.json();if(r.ok&&d.ok&&d.order_status==='paid'){const clean=new URL(location.href);['payment_id','collection_id','collection_status','payment_type','merchant_order_id','status','preference_id','site_id','processing_mode','merchant_account_id','mp'].forEach(k=>clean.searchParams.delete(k));history.replaceState({},'',clean.pathname+clean.search);await load(false);}}catch(e){console.warn('Sync Mercado Pago:',e);}}
async function load(doSync=true){currentToken=new URLSearchParams(location.search).get('token')||'';if(!currentToken){$('#orderBox').innerHTML='<div class="empty"><b>Pedido inválido.</b></div>';return;}try{const r=await fetch('backend/api/order.php?token='+encodeURIComponent(currentToken),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Erro ao carregar pedido.');const o=d.order;currentOrder=o;const paid=o.status==='paid',mpStatus=o.mp_status||'',pendingText=mpStatus==='pending'?'Pagamento informado como pendente pelo Mercado Pago.':mpStatus==='rejected'?'O pagamento foi recusado. Você pode tentar novamente.':'O pagamento ainda não foi confirmado.';$('#orderBox').innerHTML=`<div class="order-summary"><div><small>PEDIDO</small><strong>#${o.id}</strong></div><div><small>STATUS</small><strong class="order-status ${paid?'paid':''}">${paid?'PAGO':o.status==='cancelled'?'CANCELADO':'AGUARDANDO PAGAMENTO'}</strong></div><div><small>TOTAL</small><strong>${money(o.total)}</strong></div></div><p class="order-help">${paid?'Pagamento confirmado. Seus originais estão liberados por 7 dias, com até 10 downloads por foto.':pendingText}</p>${!paid&&o.status!=='cancelled'?`<div class="payment-actions"><div id="walletBrick_container"></div><small>Checkout Pro oficial do Mercado Pago.</small><p id="paymentNotice" class="form-message"></p></div>`:''}<div class="order-items">${d.items.map(i=>`<article><img src="${esc(i.public_path)}" alt=""><div><b>${esc(i.event_name)}</b><small>${i.bib_numbers?'Peito '+esc(i.bib_numbers):'Foto #'+i.photo_id}</small><span>${money(i.unit_price)}</span></div>${paid&&i.download_url?`<a class="primary download-link" href="${esc(i.download_url)}">Baixar original</a>`:'<span class="locked">🔒 Original bloqueado</span>'}</article>`).join('')}</div>`;if(doSync)await syncReturnedPayment();if(!paid&&o.status!=='cancelled')await renderMercadoPagoWallet();}catch(e){$('#orderBox').innerHTML=`<div class="empty"><b>Não foi possível abrir o pedido.</b><span>${esc(e.message)}</span></div>`;}}
load();
